-- FUNCTION
-- 프로시저와 사용용도가 거의 비슷하다.
-- 차이점은 실행 결과를 되돌려 받을 수 있다.(RETURN)

CREATE OR REPLACE FUNCTION BONUS_CALC
(
   V_EMP EMPLOYEE.EMP_ID%TYPE
)
RETURN NUMBER 
IS
  V_SAL EMPLOYEE.SALARY%TYPE;
  V_BONUS EMPLOYEE.BONUS%TYPE;
  CALC_SAL NUMBER;
BEGIN
  SELECT E.SALARY
       , NVL(E.BONUS, 0)
    INTO V_SAL
       , V_BONUS
    FROM EMPLOYEE E
   WHERE E.EMP_ID = V_EMP;

   CALC_SAL := (V_SAL + (V_SAL * V_BONUS)) * 12;
   
   RETURN CALC_SAL;
END;
/

VARIABLE VAR_CALC NUMBER;

EXEC :VAR_CALC := BONUS_CALC('&EMP_ID'); 

PRINT VAR_CALC;

SELECT 
       E.EMP_ID
      ,E.EMP_NAME
      ,BONUS_CALC(E.EMP_ID)
   FROM EMPLOYEE E
  WHERE BONUS_CALC(E.EMP_ID) < 30000000;
  
  

  
  
  
  
  
  
  
  