-- PACKAGE 
-- 프로시저와 함수를 효율적으로 관리하기 위해 묶는 단위
-- 패키지명.함수명() <- 이런식으로 사용
-- DBMS_OUTPUT.PUT_LINE();

DBMS_OUTPUT.PUT_LINE();

CREATE OR REPLACE PACKAGE GREEDY_PACK
IS
   PROCEDURE CURSOR_DEPT;
   FUNCTION BONUS_CALC(V_EMPID EMPLOYEE.EMP_ID%TYPE) RETURN NUMBER;
END;
/

DROP PACKAGE GREEDU_PACK;

CREATE OR REPLACE PACKAGE GREEDY_PACK
IS
   PROCEDURE SHOW_EMP;
END;
/

CREATE OR REPLACE PACKAGE BODY GREEDY_PACK
IS
   PROCEDURE SHOW_EMP
   IS
     V_EMP EMPLOYEE%ROWTYPE;
     CURSOR C1
     IS
     SELECT E.EMP_ID
          , E.EMP_NAME
          , E.EMP_NO
       FROM EMPLOYEE E;
    BEGIN
     FOR V_EMP IN C1 LOOP
       DBMS_OUTPUT.PUT_LINE('사번 : ' || V_EMP.EMP_ID || ', 이름 : '|| V_EMP.EMP_NAME || ', 주민등록번호 : '|| V_EMP.EMP_NO);
    END LOOP;
  END;
END;
/

EXEC GREEDY_PACK.SHOW_EMP;



