-- 트리거(TRIGGER)
-- 테이블에 INSERT, UPDATE, DELETE등 DML에 의해 변경될 때 
-- 자동으로 수행할 내용을 정의하여 저장한 객체이다.
SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER TRG_01
    AFTER  -- ~한 후에 
   INSERT ON EMPLOYEE
BEGIN --이걸 시작하겠다.
  DBMS_OUTPUT.PUT_LINE('신입사원이 입사했습니다.');
END;
/
SELECT * FROM EMPLOYEE;
INSERT
   INTO EMPLOYEE 
   (
   EMP_ID, EMP_NAME, EMP_NO, JOB_CODE, DEPT_CODE, BONUS, ENT_YN,
   HIRE_DATE, SAL_LEVEL, SALARY, MANAGER_ID, PHONE, ENT_DATE, EMAIL
   )
   VALUES
   (
    300,'선동일'	,621235-1985634	,'sun_di@greedy.com','01099546325','D5',
    'J1','S1',8000000,0.3,200,SYSDATE,'NULL','N'
   );
   
-- 부모 1
CREATE TABLE PRODUCT(
    PCODE NUMBER PRIMARY KEY,
    PNAME VARCHAR2(30),
    BRAND VARCHAR2(30),
    PRICE NUMBER,
    STOCK NUMBER DEFAULT 0
);
DROP TABLE PRODUCT;
-- 자식 M
CREATE TABLE PRODETIAL(
    DCODE NUMBER PRIMARY KEY,
    PCODE NUMBER,
    PDATE DATE,
    AMOUNT NUMBER,
    STATUS VARCHAR2(10) CHECK(STATUS IN('입고', '출고')),
    FOREIGN KEY(PCODE) REFERENCES PRODUCT(PCODE)
);

CREATE SEQUENCE SEQ_PCODE;
CREATE SEQUENCE SEQ_DCODE;

SELECT * FROM USER_SEQUENCES;

INSERT
   INTO PRODUCT P (P.PCODE, P.PNAME, P.BRAND,P.PRICE)
   VALUES (SEQ_PCODE.NEXTVAL, '갤력시23','삼송', 2300000);

INSERT
   INTO PRODUCT P (P.PCODE, P.PNAME, P.BRAND,P.PRICE)
   VALUES (SEQ_PCODE.NEXTVAL, '아이폰 14','사과', 2400000);
   
INSERT
   INTO PRODUCT P (P.PCODE, P.PNAME, P.BRAND,P.PRICE)
   VALUES (SEQ_PCODE.NEXTVAL, '대륙폰','샤오미', 1800000);

SELECT *
   FROM PRODUCT;
   
-- 행 트리거 : 컬럼의 각각의 행의 데이터에 행 변화가 생길때마다 실행되며, 그 데이터 행의 실제값을 제어할 수 있다.
-- 문장 트리거 : 트리거 사건에 의해 단 한번만 실행되고, 컬럼의 각 데이터 행을 제어할 수 없다.

CREATE OR REPLACE TRIGGER TRG_02
  AFTER 
  INSERT ON PRODETIAL
  FOR EACH ROW 
BEGIN
  IF :NEW.STATUS = '입고'
  THEN 
    UPDATE PRODUCT P
       SET P.STOCK = P.STOCK + :NEW.AMOUNT
     WHERE P.PCODE = :NEW.PCODE;
  END IF;
  IF :NEW.STATUS = '출고'
  THEN 
    UPDATE PRODUCT P
       SET P.STOCK = P.STOCK - :NEW.AMOUNT
     WHERE P.PCODE = :NEW.PCODE;
  END IF;
END;
/

SELECT * FROM PRODUCT;
SELECT * FROM PRODETIAL;

INSERT 
   INTO PRODETIAL P ( DCODE, PCODE, PDATE, AMOUNT, STATUS) 
   VALUES (SEQ_DCODE.NEXTVAL, 1, SYSDATE, 10, '입고');

INSERT 
   INTO PRODETIAL P ( DCODE, PCODE, PDATE, AMOUNT, STATUS) 
   VALUES (SEQ_DCODE.NEXTVAL, 2, SYSDATE, 50, '입고');

INSERT 
   INTO PRODETIAL P ( DCODE, PCODE, PDATE, AMOUNT, STATUS) 
   VALUES (SEQ_DCODE.NEXTVAL, 3, SYSDATE, 30, '입고');
INSERT 
   INTO PRODETIAL P ( DCODE, PCODE, PDATE, AMOUNT, STATUS) 
   VALUES (SEQ_DCODE.NEXTVAL, 2, SYSDATE, 15, '출고');

INSERT 
   INTO PRODETIAL P ( DCODE, PCODE, PDATE, AMOUNT, STATUS) 
   VALUES (SEQ_DCODE.NEXTVAL, 3, SYSDATE, 15, '출고');

SELECT 
        *
   FROM PRODUCT P
   JOIN PRODETIAL PD ON(P.PCODE = PD.PCODE);


